id: d407328c-dad6-49fe-98ff-70caadecf318
type: database
provider: sqlserver
name: Database
description: Example of database with SQL Server as provider
annotations:
  - namespace: c4modeler
    name: position
    value:
      container:
        x: 139
        y: 374
